1_create: ## creates an asg with two instances, dependency: terraform
	terraform apply

2_run: ## you got to create an instance on your own and replace the id in experiment.json
	chaos run experiment.json
